// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AnnaAnimalChatWebSite.Tests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("預約服務")]
    [NUnit.Framework.CategoryAttribute("web")]
    public partial class 預約服務Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "預約服務.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "預約服務", "\t為了能夠事先預定溝通時間\r\n\t身為一個要能夠請安娜一起來聊天的使用者\r\n\t我需要一個能夠預約溝通時間的表單", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("預約線上文字聊天一小時, 並有兩個寵物同伴, 希望預約在平日下午12:00~13:30")]
        public virtual void 預約線上文字聊天一小時並有兩個寵物同伴希望預約在平日下午12001330()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("預約線上文字聊天一小時, 並有兩個寵物同伴, 希望預約在平日下午12:00~13:30", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("開啟 \"to Book 來聊愛\" 頁面", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FullName",
                        "LineId",
                        "Claim",
                        "Family",
                        "AnimalStatus",
                        "AnimalAmount",
                        "A_AnimalName",
                        "A_AnimalPic",
                        "B_AnimalName",
                        "B_AnimalPic"});
            table1.AddRow(new string[] {
                        "魚尾",
                        "Kodofish",
                        "拔巴",
                        "",
                        "在世",
                        "2",
                        "斑斑",
                        "斑斑.jpg",
                        "小虎",
                        "小虎.jpg"});
#line 10
 testRunner.And("我必須先填寫基本資料", ((string)(null)), table1, "And ");
#line 13
 testRunner.And("選擇聊天方式 \"線上文字訊息\", 聊天時間 \"1hr\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("預約的時段選擇 \"平日 下午12:00~13:30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.When("當我按下確認表單後", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("應該能得到 \"送出成功\" 的訊息", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
